-- Durable, rights-aware data acquisition. Observed bars retain their price basis and source
-- precedence; sync state survives restarts so a retry resumes instead of redownloading blindly.
ALTER TABLE underlying_bar ADD COLUMN adjusted INTEGER NOT NULL DEFAULT 0;
ALTER TABLE underlying_bar ADD COLUMN quality_rank INTEGER NOT NULL DEFAULT 0;

CREATE TABLE data_sync_cursor (
  owner_key         TEXT NOT NULL,
  source_key        TEXT NOT NULL,
  symbol            TEXT NOT NULL,
  domain            TEXT NOT NULL DEFAULT 'CANDLES',
  interval_key      TEXT NOT NULL DEFAULT '1d',
  status            TEXT NOT NULL DEFAULT 'NEVER',
  requested_from    DATE,
  requested_to      DATE,
  last_success_date DATE,
  last_attempt_at   TIMESTAMPTZ,
  next_allowed_at   TIMESTAMPTZ,
  failure_count     INTEGER NOT NULL DEFAULT 0,
  rows_written      BIGINT NOT NULL DEFAULT 0,
  note              TEXT,
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (owner_key, source_key, symbol, domain, interval_key)
);
CREATE INDEX idx_data_sync_cursor_updated ON data_sync_cursor (updated_at DESC);

-- Request budgets are provider-wide, not browser-tab-local. A restart cannot forget that a
-- daily allowance was consumed and immediately repeat the same expensive calls.
CREATE TABLE provider_request_budget (
  source_key  TEXT NOT NULL,
  period_key  DATE NOT NULL,
  used_count  INTEGER NOT NULL DEFAULT 0,
  limit_count INTEGER NOT NULL,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (source_key, period_key)
);

-- Invalid rows are retained as small diagnostics, never promoted into the observed dataset.
-- payload_excerpt is capped by the writer and must not contain credentials or complete files.
CREATE TABLE data_quarantine (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id          TEXT,
  source_key      TEXT NOT NULL,
  symbol          TEXT,
  row_ref         TEXT,
  reason          TEXT NOT NULL,
  payload_excerpt TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_data_quarantine_created ON data_quarantine (created_at DESC);

-- UI-managed end-of-day maintenance. It is opt-in and per owner; the scheduler runs after the
-- close, not hourly while an unchanged daily bar is still forming.
CREATE TABLE data_sync_schedule (
  owner_key       TEXT PRIMARY KEY,
  enabled         INTEGER NOT NULL DEFAULT 0,
  source_key      TEXT NOT NULL DEFAULT 'auto',
  symbols         TEXT NOT NULL DEFAULT '',
  years           INTEGER NOT NULL DEFAULT 5,
  adjustment      TEXT NOT NULL DEFAULT 'AUTO',
  last_run_date   DATE,
  last_status     TEXT,
  last_job_id     TEXT,
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
