-- StrikeBench schema (PostgreSQL). Reworked for the research-platform direction.
-- Money is exact: integer cents in BIGINT columns; per-share prices in NUMERIC(19,4).
-- DOUBLE PRECISION appears only for non-money ratios (IV, greeks, probabilities, scores).
-- Timestamps on the paper-trading domain are ISO-8601 TEXT (the app treats them as opaque
-- strings); the new time-series and evaluation tables use TIMESTAMPTZ / DATE.

-- ---- Identity (multi-user; runs with one user today) ----
CREATE TABLE users (
  id          TEXT PRIMARY KEY,
  email       TEXT UNIQUE,
  provider    TEXT,                 -- OIDC provider, e.g. 'google'
  subject     TEXT,                 -- provider 'sub' claim
  name        TEXT,
  created_at  TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);

-- ---- Paper-trading domain (final state of the former SQLite V1+V2+V3) ----
CREATE TABLE accounts (
  id               TEXT PRIMARY KEY,
  user_id          TEXT REFERENCES users(id),   -- nullable; the single existing account links on migration
  name             TEXT NOT NULL,
  type             TEXT NOT NULL CHECK (type IN ('PAPER','LIVE')),
  starting_cash_cents BIGINT NOT NULL,
  cash_cents       BIGINT NOT NULL,
  reserved_cents   BIGINT NOT NULL DEFAULT 0,
  has_traded       INTEGER NOT NULL DEFAULT 0,
  created_at       TEXT NOT NULL,
  updated_at       TEXT NOT NULL
);
CREATE INDEX idx_accounts_user ON accounts(user_id);

CREATE TABLE trades (
  id                 TEXT PRIMARY KEY,
  account_id         TEXT NOT NULL REFERENCES accounts(id),
  symbol             TEXT NOT NULL,
  strategy           TEXT NOT NULL,
  status             TEXT NOT NULL CHECK (status IN ('ACTIVE','CLOSED','EXPIRED','DELETED')),
  qty                INTEGER NOT NULL,
  legs_json          TEXT NOT NULL,
  thesis             TEXT,
  horizon            TEXT,
  risk_mode          TEXT,
  intent             TEXT,
  shares_locked      INTEGER NOT NULL DEFAULT 0,
  entry_underlying_cents BIGINT NOT NULL,
  entry_net_premium_cents BIGINT NOT NULL, -- signed cash effect at open excl. fees: credit > 0, debit < 0
  max_loss_cents     BIGINT NOT NULL,       -- always finite for accepted trades, >= 0
  max_profit_cents   BIGINT,                -- null only for stock-backed strategies with unbounded upside
  breakevens_json    TEXT NOT NULL,
  pop_entry          DOUBLE PRECISION,
  fees_open_cents    BIGINT NOT NULL DEFAULT 0,
  fees_close_cents   BIGINT NOT NULL DEFAULT 0,
  realized_pnl_cents BIGINT,
  close_reason       TEXT,
  entry_snapshot_json TEXT NOT NULL,
  is_live            INTEGER NOT NULL DEFAULT 0,
  created_at         TEXT NOT NULL,
  closed_at          TEXT,
  updated_at         TEXT NOT NULL
);
CREATE INDEX idx_trades_account_status ON trades(account_id, status, created_at DESC);

CREATE TABLE ledger (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id     TEXT NOT NULL REFERENCES accounts(id),
  trade_id       TEXT,
  ts             TEXT NOT NULL,
  type           TEXT NOT NULL CHECK (type IN
    ('DEPOSIT','RESET','PREMIUM_OPEN','PREMIUM_CLOSE','SETTLEMENT','FEE','RESERVE_HOLD','RESERVE_RELEASE','ADJUSTMENT','STOCK_BUY','STOCK_SELL')),
  amount_cents   BIGINT NOT NULL,         -- signed; for RESERVE_* this moves reserve, not cash
  cash_after_cents     BIGINT NOT NULL,
  reserved_after_cents BIGINT NOT NULL,
  memo           TEXT
);
CREATE INDEX idx_ledger_account ON ledger(account_id, id);
CREATE INDEX idx_ledger_trade ON ledger(trade_id);

CREATE TABLE trade_marks (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trade_id        TEXT NOT NULL REFERENCES trades(id),
  ts              TEXT NOT NULL,
  underlying_px_cents BIGINT,
  close_cost_cents BIGINT,   -- signed cash effect if position were closed now, excl. fees
  unrealized_cents BIGINT,
  pop_now         DOUBLE PRECISION,
  freshness       TEXT,
  detail_json     TEXT
);
CREATE INDEX idx_marks_trade ON trade_marks(trade_id, id DESC);

CREATE TABLE positions (
  id             TEXT PRIMARY KEY,
  account_id     TEXT NOT NULL REFERENCES accounts(id),
  symbol         TEXT NOT NULL,
  shares         INTEGER NOT NULL,
  avg_cost_cents BIGINT NOT NULL,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL,
  UNIQUE(account_id, symbol)
);

CREATE TABLE audit (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts          TEXT NOT NULL,
  account_id  TEXT,
  trade_id    TEXT,
  action      TEXT NOT NULL,
  level       TEXT NOT NULL DEFAULT 'INFO' CHECK (level IN ('INFO','WARN','BLOCK','ERROR')),
  detail_json TEXT
);
CREATE INDEX idx_audit_ts ON audit(id DESC);

CREATE TABLE secrets (
  k          TEXT PRIMARY KEY,
  v          TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE settings (
  k          TEXT PRIMARY KEY,
  v          TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE live_orders (
  id               TEXT PRIMARY KEY,
  client_order_id  TEXT NOT NULL UNIQUE,
  broker_account_key TEXT NOT NULL,
  symbol           TEXT NOT NULL,
  preview_id       TEXT,
  broker_order_id  TEXT,
  status           TEXT NOT NULL,
  payload_json     TEXT NOT NULL,
  created_at       TEXT NOT NULL,
  updated_at       TEXT NOT NULL
);

CREATE TABLE backtests (
  id           TEXT PRIMARY KEY,
  user_id      TEXT REFERENCES users(id),
  created_at   TEXT NOT NULL,
  request_json TEXT NOT NULL,
  report_json  TEXT NOT NULL
);

-- ---- Market data: underlying candles + option bars ----
-- option_bar holds BOTH our own forward chain snapshots AND ingested vendor history,
-- distinguished only by `source` and the per-dimension evidence columns. This is the
-- substrate for backtests, IV-rank history, and calibration.

CREATE TABLE underlying_bar (
  symbol      TEXT NOT NULL,
  d           DATE NOT NULL,
  open        NUMERIC(19,4),
  high        NUMERIC(19,4),
  low         NUMERIC(19,4),
  close       NUMERIC(19,4) NOT NULL,
  volume      BIGINT,
  source      TEXT NOT NULL,               -- provider name, e.g. 'polygon', 'stooq', 'fixture', 'snapshot'
  observed    INTEGER NOT NULL DEFAULT 1,  -- 0 for modeled/demo (booleans are 0/1 per the Db helper convention)
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (symbol, d, source)
);

CREATE TABLE option_bar (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol        TEXT NOT NULL,
  asof          DATE NOT NULL,             -- the observation/snapshot date (EOD)
  expiration    DATE NOT NULL,
  strike        NUMERIC(19,4) NOT NULL,
  opt_type      TEXT NOT NULL CHECK (opt_type IN ('CALL','PUT')),
  bid           NUMERIC(19,4),
  ask           NUMERIC(19,4),
  last          NUMERIC(19,4),
  mark          NUMERIC(19,4),
  iv            DOUBLE PRECISION,
  delta         DOUBLE PRECISION,
  gamma         DOUBLE PRECISION,
  theta         DOUBLE PRECISION,
  vega          DOUBLE PRECISION,
  open_interest BIGINT,
  volume        BIGINT,
  underlying    NUMERIC(19,4),
  source        TEXT NOT NULL,             -- 'snapshot' (ours) | vendor name | 'model'
  -- per-dimension evidence (rolls up to a worst-of badge in the app); 0/1 per the Db helper convention
  bid_ask_observed INTEGER NOT NULL DEFAULT 0,
  iv_source     TEXT,                      -- 'vendor' | 'model' | null
  greeks_source TEXT,                      -- 'vendor' | 'model' | null
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (symbol, asof, expiration, strike, opt_type, source)
);
CREATE INDEX idx_option_bar_symbol_asof ON option_bar(symbol, asof);
CREATE INDEX idx_option_bar_symbol_exp ON option_bar(symbol, expiration);

-- ---- StrategyEvaluation: the unified, scored, evidence-labeled recommendation record ----
-- Typed columns for what we rank/query; JSONB for the rich producer sub-profiles.
CREATE TABLE strategy_evaluation (
  id              TEXT PRIMARY KEY,
  user_id         TEXT REFERENCES users(id),
  symbol          TEXT NOT NULL,
  strategy        TEXT NOT NULL,
  objective       TEXT,                    -- the ranking objective this score was computed for
  asof            TIMESTAMPTZ NOT NULL DEFAULT now(),
  score           DOUBLE PRECISION,        -- monotonic 0-100 Decision score
  ev_cents        BIGINT,
  roc             DOUBLE PRECISION,
  ann_roc         DOUBLE PRECISION,        -- carries a repeat-assumption; never the primary truth
  pop             DOUBLE PRECISION,
  assignment_prob DOUBLE PRECISION,
  capital_incremental_cents BIGINT,        -- new buying power used
  capital_economic_cents    BIGINT,        -- full economic exposure (e.g. covered-call shares)
  max_loss_cents  BIGINT,
  tail_loss_cents BIGINT,
  evidence_level  TEXT,                    -- worst-of badge: OBSERVED_* | MODELED_FROM_UNDERLYING | PAPER | DEMO_FIXTURE
  spec_json       JSONB,                   -- the StrategySpec that produced it
  candidate_json  JSONB,                   -- concrete legs + market snapshot
  capital_json    JSONB,
  volatility_json JSONB,
  risk_json       JSONB,
  management_json JSONB,                    -- mechanical management plan
  score_json      JSONB,                   -- component contributions
  evidence_json   JSONB,                   -- per-dimension evidence detail
  explanation_json JSONB,                  -- why selected, alternatives, assumptions, failure modes
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_eval_user_symbol ON strategy_evaluation(user_id, symbol, asof DESC);

-- ---- Recommendation: an evaluation surfaced to a user, plus its eventual outcome (calibration) ----
CREATE TABLE recommendation (
  id             TEXT PRIMARY KEY,
  user_id        TEXT REFERENCES users(id),
  evaluation_id  TEXT NOT NULL REFERENCES strategy_evaluation(id),
  context        TEXT,                     -- where it was shown (ideas, scout, ladder, ...)
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  outcome_status TEXT,                     -- null until resolved: WIN | LOSS | EXPIRED | ASSIGNED | CLOSED
  outcome_pnl_cents BIGINT,
  outcome_asof   TIMESTAMPTZ,
  outcome_json   JSONB
);
CREATE INDEX idx_reco_user ON recommendation(user_id, created_at DESC);
