-- A tracked real-world portfolio book. This is deliberately separate from the paper/simulation
-- accounts table: recording brokerage activity must never move practice cash or reserve.
CREATE TABLE portfolio_account (
  id                       TEXT PRIMARY KEY,
  owner_id                 TEXT NOT NULL,
  name                     TEXT NOT NULL,
  account_type             TEXT NOT NULL CHECK (account_type IN
    ('TAXABLE','TRADITIONAL_IRA','ROTH_IRA','TRADITIONAL_401K','ROTH_401K')),
  broker                   TEXT,
  lot_method               TEXT NOT NULL DEFAULT 'FIFO' CHECK (lot_method IN ('FIFO','LIFO','HIFO')),
  short_term_tax_rate_bps  INTEGER,
  long_term_tax_rate_bps   INTEGER,
  ordinary_tax_rate_bps    INTEGER,
  state_tax_rate_bps       INTEGER,
  status                   TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','ARCHIVED')),
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_portfolio_account_owner ON portfolio_account(owner_id, status, created_at);

CREATE TABLE portfolio_transaction (
  id                       TEXT PRIMARY KEY,
  portfolio_account_id     TEXT NOT NULL REFERENCES portfolio_account(id),
  occurred_at              TIMESTAMPTZ NOT NULL,
  event_type               TEXT NOT NULL CHECK (event_type IN
    ('DEPOSIT','WITHDRAWAL','TRANSFER_IN','TRANSFER_OUT','INTEREST','DIVIDEND','FEE',
     'TRADE','EXPIRATION','ASSIGNMENT','EXERCISE','ADJUSTMENT')),
  cash_effect_cents        BIGINT NOT NULL,
  fees_cents               BIGINT NOT NULL DEFAULT 0,
  tax_category             TEXT CHECK (tax_category IS NULL OR tax_category IN
    ('ORDINARY_INTEREST','ORDINARY_DIVIDEND','QUALIFIED_DIVIDEND','RETURN_OF_CAPITAL',
     'CAPITAL_GAIN_DISTRIBUTION')),
  source                   TEXT NOT NULL DEFAULT 'MANUAL' CHECK (source IN ('MANUAL','BROKER','IMPORT')),
  external_ref             TEXT,
  notes                    TEXT,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (portfolio_account_id, source, external_ref)
);
CREATE INDEX idx_portfolio_tx_account_time ON portfolio_transaction(portfolio_account_id, occurred_at DESC, id);

CREATE TABLE portfolio_transaction_leg (
  transaction_id           TEXT NOT NULL REFERENCES portfolio_transaction(id) ON DELETE RESTRICT,
  leg_no                    INTEGER NOT NULL,
  instrument_type          TEXT NOT NULL CHECK (instrument_type IN ('STOCK','OPTION')),
  action                   TEXT NOT NULL CHECK (action IN ('BUY','SELL')),
  position_effect          TEXT NOT NULL CHECK (position_effect IN ('OPEN','CLOSE')),
  symbol                   TEXT NOT NULL,
  option_type              TEXT CHECK (option_type IS NULL OR option_type IN ('CALL','PUT')),
  strike                   NUMERIC(19,4),
  expiration               DATE,
  quantity                 BIGINT NOT NULL CHECK (quantity > 0),
  multiplier               INTEGER NOT NULL CHECK (multiplier > 0),
  price                    NUMERIC(19,4) NOT NULL CHECK (price >= 0),
  gross_amount_cents       BIGINT NOT NULL,
  allocated_fee_cents      BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (transaction_id, leg_no),
  CHECK ((instrument_type='STOCK' AND option_type IS NULL AND strike IS NULL AND expiration IS NULL AND multiplier=1)
      OR (instrument_type='OPTION' AND option_type IS NOT NULL AND strike IS NOT NULL AND expiration IS NOT NULL))
);

CREATE TABLE portfolio_lot (
  id                       TEXT PRIMARY KEY,
  portfolio_account_id     TEXT NOT NULL REFERENCES portfolio_account(id),
  opening_transaction_id   TEXT NOT NULL,
  opening_leg_no           INTEGER NOT NULL,
  instrument_type          TEXT NOT NULL CHECK (instrument_type IN ('STOCK','OPTION')),
  side                     TEXT NOT NULL CHECK (side IN ('LONG','SHORT')),
  symbol                   TEXT NOT NULL,
  option_type              TEXT,
  strike                   NUMERIC(19,4),
  expiration               DATE,
  opened_at                TIMESTAMPTZ NOT NULL,
  original_quantity        BIGINT NOT NULL CHECK (original_quantity > 0),
  remaining_quantity       BIGINT NOT NULL CHECK (remaining_quantity >= 0),
  original_open_amount_cents BIGINT NOT NULL CHECK (original_open_amount_cents >= 0),
  remaining_open_amount_cents BIGINT NOT NULL CHECK (remaining_open_amount_cents >= 0),
  status                   TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','CLOSED','ROLLED')),
  FOREIGN KEY (opening_transaction_id, opening_leg_no)
    REFERENCES portfolio_transaction_leg(transaction_id, leg_no)
);
CREATE INDEX idx_portfolio_lot_open ON portfolio_lot(portfolio_account_id, status, symbol, instrument_type);

CREATE TABLE portfolio_lot_match (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  portfolio_account_id     TEXT NOT NULL REFERENCES portfolio_account(id),
  lot_id                   TEXT NOT NULL REFERENCES portfolio_lot(id),
  closing_transaction_id   TEXT NOT NULL,
  closing_leg_no           INTEGER NOT NULL,
  quantity                 BIGINT NOT NULL CHECK (quantity > 0),
  opened_at                TIMESTAMPTZ NOT NULL,
  closed_at                TIMESTAMPTZ NOT NULL,
  open_amount_cents        BIGINT NOT NULL,
  close_amount_cents       BIGINT NOT NULL,
  realized_gain_cents      BIGINT NOT NULL,
  holding_term             TEXT NOT NULL CHECK (holding_term IN ('SHORT_TERM','LONG_TERM','ROLLED')),
  wash_sale_adjustment_cents BIGINT NOT NULL DEFAULT 0,
  FOREIGN KEY (closing_transaction_id, closing_leg_no)
    REFERENCES portfolio_transaction_leg(transaction_id, leg_no)
);
CREATE INDEX idx_portfolio_match_account_close ON portfolio_lot_match(portfolio_account_id, closed_at DESC);

CREATE TABLE portfolio_valuation (
  id                       TEXT PRIMARY KEY,
  portfolio_account_id     TEXT NOT NULL REFERENCES portfolio_account(id),
  as_of                    TIMESTAMPTZ NOT NULL,
  cash_cents               BIGINT,
  securities_value_cents   BIGINT,
  total_value_cents        BIGINT NOT NULL,
  source                   TEXT NOT NULL DEFAULT 'MANUAL' CHECK (source IN ('MANUAL','BROKER','CALCULATED','IMPORT')),
  external_ref             TEXT,
  notes                    TEXT,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (portfolio_account_id, source, as_of)
);
CREATE INDEX idx_portfolio_valuation_account_time ON portfolio_valuation(portfolio_account_id, as_of);
