-- Preserve both the actual acquisition timestamp and the tax holding-period timestamp. A wash
-- sale carries the latter while the former remains the anchor for the +/-30 day replacement test.
ALTER TABLE portfolio_lot ADD COLUMN acquired_at TIMESTAMPTZ;
UPDATE portfolio_lot SET acquired_at=opened_at;
ALTER TABLE portfolio_lot ALTER COLUMN acquired_at SET NOT NULL;

-- Exact, auditable allocation from one realized loss match to one replacement-lot slice.
CREATE TABLE portfolio_wash_sale_allocation (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  portfolio_account_id     TEXT NOT NULL REFERENCES portfolio_account(id),
  loss_match_id            BIGINT NOT NULL REFERENCES portfolio_lot_match(id),
  replacement_lot_id       TEXT NOT NULL REFERENCES portfolio_lot(id),
  quantity                 BIGINT NOT NULL CHECK (quantity > 0),
  adjustment_cents         BIGINT NOT NULL CHECK (adjustment_cents > 0),
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (loss_match_id, replacement_lot_id)
);
CREATE INDEX idx_portfolio_wash_loss ON portfolio_wash_sale_allocation(loss_match_id);
CREATE INDEX idx_portfolio_wash_replacement ON portfolio_wash_sale_allocation(replacement_lot_id);
